"""add_google_refresh_token_to_user

Revision ID: 21270b3f4b2a
Revises: 0002
Create Date: 2026-04-29 23:43:25.587930

"""
from alembic import op
import sqlalchemy as sa


revision = '21270b3f4b2a'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
