"""add_connected_account_model

Revision ID: 427ef9caafac
Revises: 21270b3f4b2a
Create Date: 2026-04-30 00:53:42.368809

"""
from alembic import op
import sqlalchemy as sa


revision = '427ef9caafac'
down_revision = '21270b3f4b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_history_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_email'), 'connected_accounts', ['email'], unique=False)
    op.create_index(op.f('ix_connected_accounts_id'), 'connected_accounts', ['id'], unique=False)
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_connected_accounts_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_email'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###
