"""added account email verification and password reset

Revision ID: a8faead918b5
Revises: ec86383315c7
Create Date: 2026-04-30 06:05:31.262489

"""
from alembic import op
import sqlalchemy as sa


revision = 'a8faead918b5'
down_revision = 'ec86383315c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
