"""add_icp_blueprint

Revision ID: b7b364e79bcc
Revises: 452eec4966e0
Create Date: 2026-05-13 15:47:26.441369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b7b364e79bcc'
down_revision = '452eec4966e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_blueprints_id'), 'icp_blueprints', ['id'], unique=False)
    op.create_index(op.f('ix_icp_blueprints_user_id'), 'icp_blueprints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_icp_blueprints_user_id'), table_name='icp_blueprints')
    op.drop_index(op.f('ix_icp_blueprints_id'), table_name='icp_blueprints')
    op.drop_table('icp_blueprints')
    # ### end Alembic commands ###
