"""modified connected account models to monitor active watching

Revision ID: ec86383315c7
Revises: 427ef9caafac
Create Date: 2026-04-30 02:57:19.552045

"""
from alembic import op
import sqlalchemy as sa


revision = 'ec86383315c7'
down_revision = '427ef9caafac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('is_watching', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_accounts', 'is_watching')
    # ### end Alembic commands ###
